// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFcw2l3QBBqkMSulpHaKZPe7xS36IptFI',
    appId: '1:369421870081:web:9ad5a25dba38a47e3c8c00',
    messagingSenderId: '369421870081',
    projectId: 'budgeting-project-jkt01',
    authDomain: 'budgeting-project-jkt01.firebaseapp.com',
    storageBucket: 'budgeting-project-jkt01.firebasestorage.app',
    measurementId: 'G-BTPJCV59W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHYgE4coL4F4ZMsWzrSDemplUuBNRD3_A',
    appId: '1:369421870081:android:833fffe53a1420a73c8c00',
    messagingSenderId: '369421870081',
    projectId: 'budgeting-project-jkt01',
    storageBucket: 'budgeting-project-jkt01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDoXeGzH37LxY4YeoiaMB6eYK78zXNfQ',
    appId: '1:369421870081:ios:211af633e39c79d23c8c00',
    messagingSenderId: '369421870081',
    projectId: 'budgeting-project-jkt01',
    storageBucket: 'budgeting-project-jkt01.firebasestorage.app',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDoXeGzH37LxY4YeoiaMB6eYK78zXNfQ',
    appId: '1:369421870081:ios:211af633e39c79d23c8c00',
    messagingSenderId: '369421870081',
    projectId: 'budgeting-project-jkt01',
    storageBucket: 'budgeting-project-jkt01.firebasestorage.app',
    iosBundleId: 'com.example.budgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFcw2l3QBBqkMSulpHaKZPe7xS36IptFI',
    appId: '1:369421870081:web:45af285ce88304183c8c00',
    messagingSenderId: '369421870081',
    projectId: 'budgeting-project-jkt01',
    authDomain: 'budgeting-project-jkt01.firebaseapp.com',
    storageBucket: 'budgeting-project-jkt01.firebasestorage.app',
    measurementId: 'G-1BECWC0GTJ',
  );
}
